#!/usr/bin/env node
import chalk from 'chalk';
import fs from 'fs-extra';
import path from 'path';

export function printBanner() {
  console.log(chalk.cyan(`
███╗   ██╗ █████╗ ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗
████╗  ██║██╔══██╗████╗  ██║██╔════╝ ██║   ██║██╔══██╗██╔══██╗██╔══██╗
██╔██╗ ██║███████║██╔██╗ ██║██║  ███╗██║   ██║███████║██████╔╝██║  ██║
██║╚██╗██║██╔══██║██║╚██╗██║██║   ██║██║   ██║██╔══██║██╔══██╗██║  ██║
██║ ╚████║██║  ██║██║ ╚████║╚██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝
╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝
`));
}

export function printScoreBar(score, threshold) {
  const BAR_WIDTH = 20;
  const filled = Math.round((score / 100) * BAR_WIDTH);
  const empty = BAR_WIDTH - filled;
  const bar = '█'.repeat(filled) + '░'.repeat(empty);
  const isBlocked = score >= threshold;
  const label = isBlocked ? 'HIGH RISK - TRADE BLOCKED' : 'LOW RISK - TRADE CLEARED';
  const color = isBlocked ? chalk.red : chalk.green;

  console.log(chalk.bold('\nNANSHIELD RISK SCORE'));
  console.log(color(`${bar}  ${score}/100  [${label}]`));
}

export function printFlags(flags) {
  if (!flags || flags.length === 0) return;
  console.log(chalk.bold('\nRISK FLAGS'));
  for (const { emoji, label, detail, points } of flags) {
    const paddedLabel = label.padEnd(24);
    const pts = points > 0 ? chalk.red(`+${points}pts`) : chalk.green(`${points}pts`);
    console.log(`${emoji} ${chalk.bold(paddedLabel)} ${detail.padEnd(44)} ${pts}`);
  }
}

export function printVerdict(score, threshold) {
  const isBlocked = score >= threshold;
  console.log('');
  if (isBlocked) {
    console.log(chalk.red(`⛔ TRADE BLOCKED — Score exceeds threshold (${threshold}). Use --force to override.`));
  } else {
    console.log(chalk.green(`✅ TRADE CLEARED — Risk score within safe threshold.`));
  }
}

export function printWatchAlert(timestamp, score, threshold, change) {
  const isBlocked = score >= threshold;
  const timeStr = new Date(timestamp).toLocaleTimeString('en-US', { hour12: false });
  const icon = isBlocked ? '⛔' : '✅';
  const direction = change >= 0 ? '+' : '';
  const msg = `[${timeStr}] Score: ${score} ${icon} ALERT — SM holdings dropped ${direction}${change}% in 5min`;
  console.log(isBlocked ? chalk.red(msg) : chalk.yellow(msg));
}

export function writeReport(token, chain, score, flags, verdict, callLog = [], outputPath = './NANSHIELD-REPORT.md') {
  const timestamp = new Date().toISOString();
  const isBlocked = verdict === 'BLOCKED';

  const flagRows = (flags || [])
    .map(({ emoji, label, detail, points }) =>
      `| ${emoji} ${label} | ${detail} | ${points > 0 ? `+${points}` : points} |`
    )
    .join('\n');

  const flagTable = flagRows
    ? `| Flag | Detail | Points |\n|------|--------|--------|\n${flagRows}`
    : '_No flags raised._';

  const verdictLine = isBlocked
    ? `⛔ **TRADE BLOCKED** — Score exceeds threshold. Use \`--force\` to override.`
    : `✅ **TRADE CLEARED** — Risk score within safe threshold.`;

  const report = `# NanGuard Risk Report

**Token:** \`${token}\`
**Chain:** ${chain}
**Timestamp:** ${timestamp}
**Score:** ${score}/100
**Verdict:** ${verdictLine}

---

## Risk Score

\`\`\`
${'█'.repeat(Math.round((score / 100) * 20))}${'░'.repeat(20 - Math.round((score / 100) * 20))}  ${score}/100
\`\`\`

---

## Risk Flags

${flagTable}

---

## API Call Log

| # | Command | Status | Time |
|---|---------|--------|------|
${(callLog || []).map(({ callNum, command, status, ms }) =>
  `| ${callNum} | \`${command.length > 60 ? command.slice(0, 57) + '...' : command}\` | ${status === 'ok' ? '✓' : '✗'} | ${ms}ms |`
).join('\n')}

---

_Generated by NanGuard_
`;

  const resolvedPath = path.resolve(outputPath);
  fs.outputFileSync(resolvedPath, report);
  console.log(chalk.cyan(`\nReport written to ${resolvedPath}`));
}
